apiVersion: v1
kind: Namespace
metadata:
  name: kube-events
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kube-events
  namespace: kube-events
spec:
  type: bindings.kubernetes
  metadata:
    - name: namespace
      value: kube-events
    - name: resyncPreiodInSec
      value: "5"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dapr-dashboard-ingress
  namespace: dapr-system
  annotations:
    kubernetes.io/ingress.class: "ambassador"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: dapr-dashboard
              servicePort: 8080
